const products = [
  { id: 'p1', name: 'Head-Lamp-XXX', category: 'lainnya', price: 25.99, image_url: 'assets/produk/lainnya/Head-Lamp-XXX.jpg', description: 'Reliable headlamp for all your adventures.' },
  { id: 'p2', name: 'Head-Lamp', category: 'lainnya', price: 19.99, image_url: 'assets/produk/lainnya/Head-Lamp.jpg', description: 'A trusty companion for dark trails.' },
  { id: 'p3', name: 'Kompor-Camping', category: 'lainnya', price: 45.50, image_url: 'assets/produk/lainnya/Kompor-Camping.jpg', description: 'Compact and efficient camping stove.' },
  { id: 'p4', name: 'Kompor-Portable', category: 'lainnya', price: 35.00, image_url: 'assets/produk/lainnya/Kompor-Portable.jpg', description: 'Lightweight stove for quick meals.' },
  { id: 'p5', name: 'Lampu-Tenda', category: 'lainnya', price: 15.75, image_url: 'assets/produk/lainnya/Lampu-Tenda.jpg', description: 'Brightens up your tent at night.' },
  { id: 'p6', name: 'Lensatic-Compas', category: 'lainnya', price: 22.00, image_url: 'assets/produk/lainnya/Lensatic-Compas.jpg', description: 'Essential for navigation.' },
  { id: 'p7', name: 'Pisau-lipat-XYZ', category: 'lainnya', price: 18.99, image_url: 'assets/produk/lainnya/Pisau-lipat-XYZ.jpg', description: 'Versatile folding knife.' },
  { id: 'p8', name: 'Sendok-Garpu', category: 'lainnya', price: 10.00, image_url: 'assets/produk/lainnya/Sendok-Garpu.jpg', description: 'Durable utensil set.' },
  { id: 'p9', name: 'Tongkat-Gunung', category: 'lainnya', price: 29.99, image_url: 'assets/produk/lainnya/Tongkat-Gunung.jpg', description: 'Provides stability on uneven terrain.' },
  { id: 'p10', name: 'Jaket-Adventure', category: 'pakaian', price: 89.99, image_url: 'assets/produk/pakaian/Jaket-Adventure.jpg', description: 'Weather-resistant adventure jacket.' },
  { id: 'p11', name: 'Jaket-Avtech', category: 'pakaian', price: 75.00, image_url: 'assets/produk/pakaian/Jaket-Avtech.jpg', description: 'Comfortable and stylish outdoor jacket.' },
  { id: 'p12', name: 'Jaket-Gunung', category: 'pakaian', price: 99.50, image_url: 'assets/produk/pakaian/Jaket-Gunung.jpg', description: 'Insulated jacket for mountain expeditions.' },
  { id: 'p13', name: 'Jaket-JACKWOLFS', category: 'pakaian', price: 120.00, image_url: 'assets/produk/pakaian/Jaket-JACKWOLFS.jpg', description: 'High-performance Jack Wolfskin jacket.' },
  { id: 'p14', name: 'Jaket-Wolfskin', category: 'pakaian', price: 110.00, image_url: 'assets/produk/pakaian/Jaket-Wolfskin.jpg', description: 'Durable Wolfskin outdoor jacket.' },
  { id: 'p15', name: 'Adidas-Neo-AX2', category: 'sepatu', price: 150.00, image_url: 'assets/produk/sepatu/Adidas-Neo-AX2.jpg', description: 'Comfortable Adidas hiking shoes.' },
  { id: 'p16', name: 'SEPATU-DELTA-6', category: 'sepatu', price: 130.00, image_url: 'assets/produk/sepatu/SEPATU-DELTA-6-.jpg', description: 'Tactical Delta 6 boots.' },
  { id: 'p17', name: 'Sepatu-Eiger', category: 'sepatu', price: 140.00, image_url: 'assets/produk/sepatu/Sepatu-Eiger.jpg', description: 'Reliable Eiger hiking footwear.' },
  { id: 'p18', name: 'Sepatu-Merrell', category: 'sepatu', price: 165.00, image_url: 'assets/produk/sepatu/Sepatu-Merrell-.jpg', description: 'High-quality Merrell trail shoes.' },
  { id: 'p19', name: 'Sepatu', category: 'sepatu', price: 80.00, image_url: 'assets/produk/sepatu/Sepatu.jpg', description: 'Generic but sturdy hiking shoe.' },
  { id: 'p20', name: 'sepatu-converse', category: 'sepatu', price: 60.00, image_url: 'assets/produk/sepatu/sepatu-converse.jpeg', description: 'Classic Converse for casual trails.' },
  { id: 'p21', name: 'Tas-Ost-Rei', category: 'tas', price: 95.00, image_url: 'assets/produk/tas/Tas--Ost-Rei.jpg', description: 'Durable Ost Rei backpack.' },
  { id: 'p22', name: 'Tas-Consina', category: 'tas', price: 105.00, image_url: 'assets/produk/tas/Tas-Consina.jpg', description: 'Spacious Consina trekking bag.' },
  { id: 'p23', name: 'Tas-Deuter', category: 'tas', price: 125.00, image_url: 'assets/produk/tas/Tas-Deuter.jpg', description: 'Comfortable Deuter hiking backpack.' },
  { id: 'p24', name: 'Tas-Eiger', category: 'tas', price: 115.00, image_url: 'assets/produk/tas/Tas-Eiger.jpg', description: 'Versatile Eiger backpack for all needs.' },
  { id: 'p25', name: 'Tas-Moods', category: 'tas', price: 70.00, image_url: 'assets/produk/tas/Tas-Moods.jpg', description: 'Stylish Moods daypack.' },
  { id: 'p26', name: 'Tas-Royal-Mountain', category: 'tas', price: 130.00, image_url: 'assets/produk/tas/Tas-Royal-Mountain.jpg', description: 'Large capacity Royal Mountain expedition bag.' },
  { id: 'p27', name: 'Tenda-Camping', category: 'tenda', price: 200.00, image_url: 'assets/produk/tenda/Tenda-Camping.jpg', description: 'Easy setup camping tent.' },
  { id: 'p28', name: 'Tenda-Consina', category: 'tenda', price: 220.00, image_url: 'assets/produk/tenda/Tenda-Consina.jpg', description: 'Weatherproof Consina tent.' },
  { id: 'p29', name: 'Tenda-Dome', category: 'tenda', price: 180.00, image_url: 'assets/produk/tenda/Tenda-Dome.jpg', description: 'Classic dome tent for various conditions.' },
  { id: 'p30', name: 'Tenda-Eiger-E12', category: 'tenda', price: 250.00, image_url: 'assets/produk/tenda/Tenda-Eiger-E12.jpg', description: 'Spacious Eiger E12 family tent.' },
  { id: 'p31', name: 'Tenda-Montana', category: 'tenda', price: 190.00, image_url: 'assets/produk/tenda/Tenda-Montana.jpg', description: 'Robust Montana tent for hikers.' },
  { id: 'p32', name: 'Tenda-Summer', category: 'tenda', price: 150.00, image_url: 'assets/produk/tenda/Tenda-Summer.jpg', description: 'Lightweight summer tent.' }
];

const mountainRecommendations = [
  { id: 'm1', name: 'Mount EasyClimb', skill_level: 'Beginner', description: 'Perfect for first-timers, offering great views with a gentle slope.', image_url: 'assets/kategori/tas.png' },
  { id: 'm2', name: 'Ridge Peak Challenge', skill_level: 'Intermediate', description: 'A moderately challenging hike with rewarding panoramic views from the summit.', image_url: 'assets/kategori/sepatu.png' },
  { id: 'm3', name: 'Serenity Summit', skill_level: 'Beginner', description: 'A peaceful trail leading to a serene summit, ideal for a relaxing day out.', image_url: 'assets/kategori/pakaian.png' },
  { id: 'm4', name: 'Dragons Tooth Ascent', skill_level: 'Advanced', description: 'A strenuous and technical climb for experienced hikers seeking a thrill.', image_url: 'assets/kategori/tenda.png' }
];
